ALTER TABLE posts ADD COLUMN edit_version BIGINT NOT NULL DEFAULT 0 CHECK (edit_version >= 0);
ALTER TABLE posts ADD COLUMN edited_at TIMESTAMP;
ALTER TABLE posts ADD COLUMN content_format VARCHAR(30) NOT NULL DEFAULT 'MARKDOWN_V1';
